### ISSUE TITLE
TSAN: Generate TSAN clang rt libs for riscv64

### ISSUE THREAD

**Issue by prashanthswami** [google/android-riscv64#104]
To be at parity with other architectures in the Android NDK, we would like to have the libclang_rt.tsan-riscv64-android.so library included as part of the imported sysroot from Android (Clang Prebuilts). This is distinct from it actually _working_, which is tracked here: https://github.com/android/ndk/issues/1041 .

**Comment by pirama-arumuga-nainar** [comment]
https://reviews.llvm.org/D145214 enables tsan runtime for riscv64.

**Comment by enh-google** [comment]
seems like no-one's reviewed that change yet. @appujee --- is that something we can help with?

**Comment by appujee** [comment]
let me reach out to the author if he is still working on it.

**Comment by appujee** [comment]
nobody responded to my query on discord. I can commandeer the patch and put for review.

**Comment by appujee** [comment]
Update: The author is waiting on review as the patch is feature complete. I've pinged the reviewers

**Comment by appujee** [comment]
Update: I pinged reviewers to take another look.
Except for minor nits, the reviewers are okay with the patch but would like dvyukov to take a look. I've pinged him.
