### ISSUE TITLE
Booted to lockscreen, unable to unlock

### ISSUE THREAD

**Issue by royfranz** [google/android-riscv64#108]
Hi,

   I have built riscv AOSP and booted it on cuttlefish following the readme, getting to an android lock screen on the VNC server.  At this point I seem to be unable to interact with the booted android image.  Attempts to hold the mouse down and slide it across the bottom of the screen or up from the bottom have no effect.  The VNC mouse curser is very laggy - seems like 1-3 seconds of latency, and the displayed mouse pointer is offset from the VNC host cursor dot.
Is there some other way I should be unlocking the lock screen?
Is this level of (low) performance expected?  I'm running this on a fast x86 system.

I could not find any cuttlefish documentation regarding the VNC connection, but please point me to that if there is existing documentation.

As an aside, I also ran into issue #85 as I first built QEMU without proper accelerated video support, then ran into my host not having accelerated video.  What is the proper way to submit a patch to the README on this github project?

Thanks!

**Comment by enh-google** [comment]
> Is this level of (low) performance expected? I'm running this on a fast x86 system.

yeah, pretty much. i have 128 cores and 128 GiB of RAM, and i can unlocked, but it's still pretty janky. (remember that Java's all still interpreted for now.)

> What is the proper way to submit a patch to the README on this github project?

you can send a pull request like normal, or just suggest a change here.
