### ISSUE TITLE
clang driver: enable fast unaligned access for android

### ISSUE THREAD

**Issue by appujee** [google/android-riscv64#111]
Maybe we can add this to clang driver once we have tested it?

**Comment by appujee** [comment]
aosp testing in progress: https://android-review.googlesource.com/c/platform/build/soong/+/2734373

**Comment by enh-google** [comment]
> Maybe we can add this to clang driver once we have tested it?

oh, definitely --- any time we land something in AOSP (and we feel like it's _really_ landed and isn't going to get reverted), we should start moving it upstream. any time i _don't_ suggest that to you is a bug on my part :-)

(the alternative is that every single build system has to add these flags, which obviously doesn't scale.)

**Comment by appujee** [comment]
merged.

**Comment by appujee** [comment]
i think it is okay to keep it open as the currently used (backend) flags will be updated (to -munaligned-access) with the new toolchain.

**Comment by SiFiveHolland** [comment]
Any reason not to use `-mno-strict-align`, which is [common with GCC](https://gcc.gnu.org/onlinedocs/gcc/RISC-V-Options.html#index-mstrict-align-3)?

**Comment by prashanthswami** [comment]
Bumping this thread because the last comment mentions we'll have 'unaligned-access' in the new toolchain, and I believe we've completed a round of updates since Oct.

@appujee - should we be switching our flags to "-munaligned-access" now? WDYT about @SiFiveHolland 's comments on 'no-strict-align'?

**Comment by appujee** [comment]
yes, `-munaligned-access` flag works with the latest clang update.

**Comment by enh-google** [comment]
> I'll replace the previous workaround with -munaligned-access

is there a reason we haven't moved this into the driver yet? this flag has been in AOSP for a long time now with no problems...

**Comment by appujee** [comment]
The change landed few weeks back, https://android-review.googlesource.com/c/platform/build/soong/+/2977952 I forgot to close this bug.

**Comment by appujee** [comment]
Interestingly `-munaligned-access`  was replaced by `-mno-strict-align` in llvm upstream a few days back. Both flags were aliases. Pirama has change to that effect https://android-review.googlesource.com/c/platform/build/soong/+/3002035

**Comment by appujee** [comment]
I'll  enable the flag by default for Android. https://github.com/llvm/llvm-project/pull/85704 WIP.

**Comment by enh-google** [comment]
the llvm change was merged ... is that cherrypicked for our llvm? (and is that cherrypick in the toolchain that we're working on currently for the forthcoming ndk release, or is it for the _next_ one?)

**Comment by appujee** [comment]
it was cherry-picked to our llvm in https://android-review.googlesource.com/c/toolchain/llvm_android/+/3009313 it is not in the toolchain (clang-r522817) we are working on.

**Comment by enh-google** [comment]
@appujee --- is this in our current clang?

**Comment by appujee** [comment]
yes https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/refs/heads/main/clang-r530567/clang_source_info.md
