### ISSUE TITLE
Generating the classic RISC-V bin file

### ISSUE THREAD

**Issue by Immortalin** [google/android-riscv64#119]
The current build setup only generates AVD images, is there a way to generate the traditional RISC-V `bin` files? I want to test the OS (in shell mode) on off-the-shelf RISC-V emulators.

**Comment by enh-google** [comment]
no. 

you should be able to use something like this on the end of your launch_cvd command line to point to your custom qemu though (obviously replacing the path with the equivalent path to your qemu):
```
      --vm_manager=qemu_cli \
      --qemu_binary_dir=$ANDROID_BUILD_TOP/device/google/cuttlefish_vmm/qemu/x86_64-linux-gnu/bin
```
