### ISSUE TITLE
ART: Implement "C" extension instructions in the `Riscv64Assembler`

### ISSUE THREAD

**Issue by enh-google** [google/android-riscv64#126]
For code size reduction, it would be nice for the existing instruction functions to just emit the "C" versions if available for the given arguments. However, for certain things (thinking of the introspection Baker read barrier on arm/arm64), it would be nice to have the ability to precisely specify whether to use a 16-bit or 32-bit instruction. So, I would like to see explicit 16-bit instruction functions (say, `CLdsp()`) and a flag whether to use them automatically (say, in `Ld()`) and a way to disable the flag (say, `class ScopedNoCInstructions`).

This should include adding assembler tests and changing the `AssemblerRISCV64Test` so that we can run tests with and without the "C" extension. (Maybe define a parametrized test class and change appropriate tests from `TEST_F`s to `TEST_P` with an argument whether to use the "C" extension or not.)

Note that this can be split into several changes as we do not need to add all "C" instructions together.

**Comment by romart** [comment]
@enh-google could you please assign this issue to me?

**Comment by romart** [comment]
Gerrit review 
https://android-review.googlesource.com/c/platform/art/+/2939939
https://android-review.googlesource.com/c/platform/art/+/2939940
https://android-review.googlesource.com/c/platform/art/+/2939941
https://android-review.googlesource.com/c/platform/art/+/2939942

**Comment by romart** [comment]
Finally merged into  upstream 
https://android-review.googlesource.com/c/platform/art/+/3000792
