### ISSUE TITLE
Fix ART 850-checker-branches test with JIT

### ISSUE THREAD

**Issue by romart** [google/android-riscv64#136]
This test is one of failing tests with JIT on RISCV64 target. Seems it's worth to be fixed

@enh-google could you please assign this issue to me?

**Comment by prashanthswami** [comment]
It looks like the proposed [fix](https://android-review.googlesource.com/c/platform/art/+/2953227) has a comment that points to a different [December fix](https://android-review.googlesource.com/c/platform/art/+/2879726) that resolves this issue. Please feel free to re-open if I'm mistaken, but this issue appears resolved.
