### ISSUE TITLE
What is the level of ART support in AOSP RISCV, Please help

### ISSUE THREAD

**Issue by HaPo-yishui** [google/android-riscv64#155]
What is the current state of support for ART in AOSP Riscv? Only JIT is supported, or AOT is also supported, and what is the degree of support for both, Google please help to reply.
Thanks

**Comment by enh-google** [comment]
yes, both should work and pass all tests.

**Comment by HaPo-yishui** [comment]
Hi，enh-google：

I'm sorry, maybe I didn't understand you.
If ART supports AOT compilation, with WITH_DEXPREOPT set to true, then the corresponding .odex file should be generated in the CPU architecture directory ( such as */oat/riscv64/*.odex), but it is not generated. 
Therefore, I cannot make a normal judgment on the support of AOT compilation for aosp based on riscv architecture. Looking forward to your reply.
Thanks a lot

**Comment by HaPo-yishui** [comment]
Hi，enh-google：

I'm sorry, maybe I didn't understand you.
If ART supports AOT compilation, with WITH_DEXPREOPT set to true, then the corresponding .odex file should be generated in the CPU architecture directory ( such as */oat/riscv64/*.odex), but it is not generated. 
Therefore, I cannot make a normal judgment on the support of AOT compilation for aosp based on riscv architecture. Looking forward to your reply.
Thanks a lot

**Comment by HaPo-yishui** [comment]
Hi，enh-google：

I'm sorry, maybe I didn't understand you.
If ART supports AOT compilation, with WITH_DEXPREOPT set to true, then the corresponding .odex file should be generated in the CPU architecture directory ( such as */oat/riscv64/*.odex), but it is not generated. 
Therefore, I cannot make a normal judgment on the support of AOT compilation for aosp based on riscv architecture. Looking forward to your reply.
Thanks a lot

**Comment by HaPo-yishui** [comment]
Hi，enh-google：

I'm sorry, maybe I didn't understand you.
If ART supports AOT compilation, with WITH_DEXPREOPT set to true, then the corresponding .odex file should be generated in the CPU architecture directory ( such as */oat/riscv64/*.odex), but I find it is not generated. 
Therefore, I cannot make a normal judgment on the support of AOT compilation for aosp based on riscv architecture. Looking forward to your reply.
Thanks a lot

**Comment by enh-google** [comment]
building aosp main with
```
    . build/envsetup.sh
    lunch aosp_cf_riscv64_phone-trunk_staging-userdebug
    m
```
leaves a lot of compiled oat files in a variety of directories:
```
    out/target/product/vsoc_riscv64/system/framework/riscv64/ (boot image)
    out/target/product/vsoc_riscv64/system/framework/oat/riscv64/ (system server, Mainline modules)
    out/target/product/vsoc_riscv64/system/{app,priv-app}/<app-name>/oat/riscv64/
    out/target/product/vsoc_riscv64/system_other/{product,system,system_ext}/{app,priv-app}/<app-name>/oat/riscv64/
    out/target/product/vsoc_riscv64/vendor/priv-app/<app-name>/oat/riscv64/
```
are you _sure_ you have `WITH_DEXPREOPT` set (and have done a full build with that)?

**Comment by HaPo-yishui** [comment]
> building aosp main with
> 
> ```
>     . build/envsetup.sh
>     lunch aosp_cf_riscv64_phone-trunk_staging-userdebug
>     m
> ```
> 
> leaves a lot of compiled oat files in a variety of directories:
> 
> ```
>     out/target/product/vsoc_riscv64/system/framework/riscv64/ (boot image)
>     out/target/product/vsoc_riscv64/system/framework/oat/riscv64/ (system server, Mainline modules)
>     out/target/product/vsoc_riscv64/system/{app,priv-app}/<app-name>/oat/riscv64/
>     out/target/product/vsoc_riscv64/system_other/{product,system,system_ext}/{app,priv-app}/<app-name>/oat/riscv64/
>     out/target/product/vsoc_riscv64/vendor/priv-app/<app-name>/oat/riscv64/
> ```
> 
> are you _sure_ you have `WITH_DEXPREOPT` set (and have done a full build with that)?

Tks, WITH_DEXPREOPT has been set to true:
![Image](https://github.com/user-attachments/assets/862cbf10-5994-47fa-9a57-040fc8104511)

Then a full build is done, a lot of compiled oat files in a variety of directories are generated:
![Image](https://github.com/user-attachments/assets/1be8aa56-a055-49f5-8707-18df113be3a1)

Thank you for your assistance

**Comment by enh-google** [comment]
> If ART supports AOT compilation, with WITH_DEXPREOPT set to true, then the corresponding .odex file should be generated in the CPU architecture directory ( such as /oat/riscv64/.odex), but I find it is not generated.

i think you're looking for the wrong files ... you want `.oat` files, not `.odex`.

**Comment by HaPo-yishui** [comment]
> > If ART supports AOT compilation, with WITH_DEXPREOPT set to true, then the corresponding .odex file should be generated in the CPU architecture directory ( such as /oat/riscv64/.odex), but I find it is not generated.
> 
> i think you're looking for the wrong files ... you want `.oat` files, not `.odex`.

 ===> 
I only see that the corresponding .oat files is generated in the framework directory, but not in other directories:

![Image](https://github.com/user-attachments/assets/09632024-2dd6-4b53-8390-e851fd0b0091)

Can you give me the reason why the .oat files are not generated? TKS

**Comment by enh-google** [comment]
the ART folks say:

Our oat files are both .oat (for boot images) and .odex (for everything else - for compatibility reasons). So, the screenshot with red arrows pointing to .odex files is correct. Those are indeed oat files.

Apps seem to be compiled without app images, therefore the search for "*.art" does not find compiled artifacts for apps.

Searching for "*.vdex" is an excellent way to find all `dex2oat` output locations. Each .oat and .odex file should have a corresponding .vdex file. However, apps compiled with `--compiler-filter=verify` shall have a .vdex file without .odex.

**Comment by HaPo-yishui** [comment]
Thank you for your reply. There is no doubt about it. TKS
