### ISSUE TITLE
llvm: prebuilts for hwasan support

### ISSUE THREAD

**Issue by enh-google** [google/android-riscv64#16]
when https://github.com/riscv/riscv-j-extension lands, we'll want to make sure we have working hwasan support.

**Comment by petrhosek** [comment]
HWASan support for RISC-V was implemented in the following series of patches:

[[RISC-V][HWASAN] Enable HWASAN for RISC-V architecture](https://reviews.llvm.org/D131345) 
[[RISC-V][HWASAN] Adjust lit test support for RISC-V HWASAN feature](https://reviews.llvm.org/D131344) 
[[RISC-V][HWASAN] Add support for HWASAN code instrumentation for RISC-V](https://reviews.llvm.org/D131575) 
[[RISC-V][HWASAN] Support tagging global variables for RISC-V HWASAN](https://reviews.llvm.org/D132995) 
[[RISC-V][HWASAN] Don't explicitly load GOT entry to call hwasan mismatch routine](https://reviews.llvm.org/D132994) 
[[RISC-V][HWASAN] Add support for lowering HWASAN intrinsic for RISC-V](https://reviews.llvm.org/D131343) 
[[RISC-V][HWASAN] Save sp address at the start of tag mismatch routine](https://reviews.llvm.org/D131574) 
[[RISC-V][HWASAN] Add runtime support for HWASAN for RISC-V](https://reviews.llvm.org/D131342) 
[[RISC-V][HWASAN] Add tag mismatch routines for HWASAN required for RISC-V](https://reviews.llvm.org/D131341) 
[[RISC-V][HWASAN] Add intrinsics required for HWASAN support for RISC-V](https://reviews.llvm.org/D131340) 
[[Triple] Add llvm::Triple::isRISCV{32,64}](https://reviews.llvm.org/D131339)

**Comment by enh-google** [comment]
yeah, hopefully the only thing we'll have to do (beyond "wait for hardware to test on") is just making sure we're building and shipping the necessarily prebuilts... (by which i _think_ i mean the LLVM toolchain team's build [and eventually the NDK team's] --- i'm assuming that the Android build system will "just work", but that may not be true.)

**Comment by enh-google** [comment]
@appujee for the LLVM side of prebuilts, since that'll have to come first.

**Comment by pirama-arumuga-nainar** [comment]
We already build some runtimes in the AOSP toolchain.  The next clang update will have the hwasan prebuilts:

```
llvm-toolchain $ find out/install/linux-x86/clang-dev/ -iname "*hwasan*" | grep riscv64
out/install/linux-x86/clang-dev/lib/clang/16.0.3/lib/linux/libclang_rt.hwasan-riscv64-android.so
out/install/linux-x86/clang-dev/lib/clang/16.0.3/lib/linux/libclang_rt.hwasan-preinit-riscv64-android.a
out/install/linux-x86/clang-dev/lib/clang/16.0.3/lib/linux/libclang_rt.hwasan-riscv64-android.a.syms
out/install/linux-x86/clang-dev/lib/clang/16.0.3/lib/linux/libclang_rt.hwasan-riscv64-android.a
out/install/linux-x86/clang-dev/lib/clang/16.0.3/lib/linux/libclang_rt.hwasan_cxx-riscv64-android.a
out/install/linux-x86/clang-dev/lib/clang/16.0.3/lib/linux/libclang_rt.hwasan_cxx-riscv64-android.a.syms
```

**Comment by enh-google** [comment]
those seem to be checked in, so i'm assuming there's nothing for us to do here other than "wait for capable hardware"?
