### ISSUE TITLE
llvm: make sure https://reviews.llvm.org/D131230 "[RISCV] Allow mismatched SmallDataLimit and use Min for conflicting values" gets merged

### ISSUE THREAD

**Issue by enh-google** [google/android-riscv64#19]
already too late for our january llvm update, but it would be nice to have https://reviews.llvm.org/D131230 "[RISCV] Allow mismatched SmallDataLimit and use Min for conflicting values" merged upstream in time for our next llvm update...

**Comment by appujee** [comment]
Merged

**Comment by appujee** [comment]
https://reviews.llvm.org/rGaf128791464810123bcd60a6d9d0902b5c550aef

**Comment by appujee** [comment]
We still need to cherry-pick this to llvm-android
