### ISSUE TITLE
llvm: make LTO work

### ISSUE THREAD

**Issue by enh-google** [google/android-riscv64#22]
(internal bug http://b/254713216)

currently worked around by disabling LTO, but we should fix that.

**Comment by enh-google** [comment]
@appujee

**Comment by pvchupin** [comment]
@appujee, @pirama-arumuga-nainar, can we have bug description added here?

**Comment by topperc** [comment]
ABI and mcpu/march for LTO is currently broken

Related
https://reviews.llvm.org/D132843
https://reviews.llvm.org/D71387
https://reviews.llvm.org/D72245
https://reviews.llvm.org/D102582
https://reviews.llvm.org/D106347

**Comment by appujee** [comment]
we were able to build with lto when emulated tls is disabled.

**Comment by appujee** [comment]
> ABI and mcpu/march for LTO is currently broken
> 
> Related https://reviews.llvm.org/D132843 https://reviews.llvm.org/D71387 https://reviews.llvm.org/D72245 https://reviews.llvm.org/D102582 https://reviews.llvm.org/D106347

thanks for sharing this. probably one of these patches fixes the warning  (`Hard-float 'd' ABI can't be used for a target that doesn't support the D instruction set extension (ignoring target-abi)`) we are getting when building with thinlto

**Comment by appujee** [comment]
created task for mpcu/march issues: https://github.com/google/android-riscv64/issues/61

**Comment by enh-google** [comment]
okay, we've re-enabled LTO for the platform (https://android-review.googlesource.com/2591987) and there's #61 for the remaining work here, so closing this bug...
