### ISSUE TITLE
llvm: fix emutls for risc-v (probably not?)

### ISSUE THREAD

**Issue by enh-google** [google/android-riscv64#47]
Android's build system's global default is emutls because all the other architectures shipped before we had elf tls. there's no reason for risc-v to use emutls (but see https://github.com/google/android-riscv64/issues/3 for exactly what we'll use instead), but it's a bit odd that emutls is completely broken, and might cause porting issues for others (apps/middleware) who're also explicitly specifying emutls in their build systems?

**Comment by brad0** [comment]
This has been fixed upstream with 16 and newer.
