### ISSUE TITLE
simpleperf

### ISSUE THREAD

**Issue by enh-google** [google/android-riscv64#48]
(googlers: see internal bug http://b/267670561)

Currently simpleperf uses external/llvm, which is too old to build on riscv.
So currently simpleperf is disabled on riscv, in system/extras/simpleperf/Android.bp L69.
To fix it, we need to export llvm libraries needed by simpleperf (listed in Android.bp L34) in clang prebuilts.
And switch simpleperf to the prebuilt libraries.

**Comment by unicornx** [comment]
> (see internal bug http://b/267670561)

I can't access this internal URL, how can we learn about the issue such like this?
