### ISSUE TITLE
ship libFuzzer.a

### ISSUE THREAD

**Issue by appujee** [google/android-riscv64#50]
both arm64 and x86_64 ship this in `prebuilts/clang/host/linux-x86/clang-r475365/runtimes_ndk_cxx/`

**Comment by appujee** [comment]
cc: @pirama-arumuga-nainar do we need to ship libFuzzer in RISC-V?

**Comment by enh-google** [comment]
prebuilts/clang/host/linux-x86/clang-r498229b/runtimes_ndk_cxx/riscv64 lgtm, so i think this is done now?

**Comment by appujee** [comment]
yes https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/refs/heads/main/clang-r498229b/runtimes_ndk_cxx/riscv64/
