### ISSUE TITLE
security: software shadow call stack support

### ISSUE THREAD

**Issue by samitolvanen** [google/android-riscv64#52]
Similarly to CFI, until #14 arrives, we should support [SCS](https://clang.llvm.org/docs/ShadowCallStack.html). [Clang support](https://reviews.llvm.org/D84414) seems to be there, but bionic implements runtime only for AArch64 right now. Changes to `__init_shadow_call_stack` and the `setjmp` implementation are probably needed at least.

**Comment by samitolvanen** [comment]
From @enh-google: https://r.android.com/q/topic:%22rv64-scs%22

**Comment by enh-google** [comment]
done for now, but see https://github.com/google/android-riscv64/issues/72 for some follow-up work as we switch from x18 to gp.
