### ISSUE TITLE
Fix RISC-V TLS bugs in llvm upstream

### ISSUE THREAD

**Issue by appujee** [google/android-riscv64#57]
https://github.com/llvm/llvm-project/issues?q=is%3Aopen+label%3Abackend%3ARISC-V++label%3Abug

**Comment by appujee** [comment]
- [ ] Introduce `-fno-emulated-tls` by default to clang for RISC-V
- [ ] Error on `-femulated-tls` passed for RISC-V targets

**Comment by brad0** [comment]
This has been fixed upstream..

[https://github.com/llvm/llvm-project/commit/f5e63f8fc9f492944b8432d80c1c49051a7d600a](https://github.com/llvm/llvm-project/commit/f5e63f8fc9f492944b8432d80c1c49051a7d600a)

**Comment by appujee** [comment]
Thanks for the update, marked both sub tasks as complete.

**Comment by brad0** [comment]
> This has been fixed upstream..
> 
> [llvm/llvm-project@f5e63f8](https://github.com/llvm/llvm-project/commit/f5e63f8fc9f492944b8432d80c1c49051a7d600a)

To add to that I have had this back ported to 16.
