### ISSUE TITLE
investigate if llvm requires any changes to make LR/SC sequence sequentially consistent 

### ISSUE THREAD

**Issue by appujee** [google/android-riscv64#74]
See if the change proposed in the [patch](https://github.com/hboehm/riscv-isa-manual/pull/1/files) is already implemented in llvm or it needs to be done.

**Comment by asb** [comment]
This definitely isn't implemented in LLVM so far (we very directly implement the mappings in table A.6). I understand there's a desire to move that table outside the spec, e.g. to the psABI repo. To implement this change in LLVM, I think we'd need these patches to make it into the upstream riscv-isa-manual, an updated mapping table to be agreed, and some discussion about the backwards compatibility of the change (i.e. if we changed the default lowering to these new forms, would you be able to mix with code compiled under the old lowerings without breaking the memory model properties).

**Comment by appujee** [comment]
yeah looks like it.
