### ISSUE TITLE
Fix default usage of reserved register

### ISSUE THREAD

**Issue by appujee** [google/android-riscv64#78]
First, ~X27~ X3 needs to be reserved. This is blocked on: https://reviews.llvm.org/D146463

- [x] in llvm-project: X3 is already reserved by default and lld doesn't enable relax-gp by default.
- [x] update bionic: https://android-review.git.corp.google.com/c/platform/bionic/+/2526531
- [x] update ART: https://android-review.git.corp.google.com/c/platform/art/+/2535780

**Comment by enh-google** [comment]
not this one :-)
```
lib/hwasan/hwasan_setjmp_riscv64.S:  fsd   fs11, 25<<3(x10)
```
remember that we'll need to update bionic and ART if we make this change too.

(is libffi affected?)

**Comment by appujee** [comment]
> not this one :-) lib/hwasan/hwasan_setjmp_riscv64.S:  fsd   fs11, 25<<3(x10)

striked it out.

> (is libffi affected?)

doesn't seem like it: https://github.com/libffi/libffi/blob/master/src/riscv/sysv.S

**Comment by enh-google** [comment]
> striked it out.

seems to have affected the wrong one?

**Comment by MaoHan001** [comment]
What is S11/X27 reserved for? I haven't seen any related topics. I previously only saw that the software SCS requires the use of S2/X18.

**Comment by enh-google** [comment]
@appujee --- given that this bug is marked as blocking #81 do we actually _need_ the kernel work here? that seems orthogonal?

**Comment by appujee** [comment]
makes sense. I've removed the item tracking kernel patches.
