### ISSUE TITLE
compiler must-haves for RISCV-android

### ISSUE THREAD

**Issue by appujee** [google/android-riscv64#81]
we can fairly easily add extensions to the compiler driver's android-riscv64 target triples (at least until we add riscv64 to CTS/CDD!), but there's some more fundamental psabi-type work that needs to be finished before we can give anyone even a preliminary NDK:

- [x] https://github.com/google/android-riscv64/issues/9
- [x] https://github.com/google/android-riscv64/issues/57
- [x] Specify platform reserved register in clang driver (https://github.com/riscv-non-isa/riscv-elf-psabi-doc/pull/371, https://github.com/riscv-non-isa/riscv-elf-psabi-doc/issues/370)
- [x] Atomic https://github.com/riscv/riscv-isa-manual/pull/992 https://github.com/riscv-non-isa/riscv-elf-psabi-doc/pull/378

(and anyone hacking together their own ndk before these are fixed should be aware that they'll have to rebuild everything at some point.)

**Comment by appujee** [comment]
Atomic fixes have been merged in the latest llvm-android. https://android-review.googlesource.com/c/toolchain/llvm_android/+/2631670

**Comment by enh-google** [comment]
we already have a separate bug for adding V to the driver, i think, and Zba/Zbs are already in (llvm, if not in aosp yet), so we can probably close this bug (unless you want to include Zba/Zbs/V here too)?

**Comment by appujee** [comment]
okay to close this i guess.
