### ISSUE TITLE
[Question] how to use vncviewer to connect to cuttlefish from Windows

### ISSUE THREAD

**Issue by unicornx** [google/android-riscv64#90]
hi, describing my env as below:

Machine A(My laptop, Windows) <--> Machine B(Build server, ubuntu)

I have launched cuttlefish on B, and I want to use vncviewer from A to connect to B, but failed (timeout). What should I do to handle this?

A and B are in local network. I tried run vncvidwer on Machine B locally and it works (`vncviewer localhost:6444`).

I logined in B remotely through SSH from A and launched cuttlefish with: `launch_cvd -cpus=8 --memory_mb=8192 --gpu_mode=drm_virgl -qemu_binary_dir=/home/u/bin/qemu-7.2.0/bin`.

vncviewer configuration on A:
![image](https://github.com/google/android-riscv64/assets/2476165/969c4d16-4792-4b69-8e80-000f89ef51b2)

**Comment by enh-google** [comment]
no idea, we don't use Windows at all. maybe some kind of firewall issue?

**Comment by nylon7** [comment]
Hi @unicornx ,

maybe you can try this.

vim device/google/cuttlefish/host/libs/vm_manager/qemu_manager.cpp 

```
--- a/host/libs/vm_manager/qemu_manager.cpp
+++ b/host/libs/vm_manager/qemu_manager.cpp
@@ -413,11 +413,11 @@ Result<std::vector<MonitorCommand>> QemuManager::StartCommands(
     qemu_cmd.AddParameter("egl-headless");

     qemu_cmd.AddParameter("-vnc");
-    qemu_cmd.AddParameter("127.0.0.1:", instance.qemu_vnc_server_port());
+    qemu_cmd.AddParameter("0.0.0.0:", instance.qemu_vnc_server_port());
   } else if (instance.gpu_mode() == kGpuModeGfxstream ||
              instance.gpu_mode() == kGpuModeGfxstreamGuestAngle) {
     qemu_cmd.AddParameter("-vnc");
-    qemu_cmd.AddParameter("127.0.0.1:", instance.qemu_vnc_server_port());
+    qemu_cmd.AddParameter("0.0.0.0:", instance.qemu_vnc_server_port());
   } else {
     qemu_cmd.AddParameter("-display");
```
