### ISSUE TITLE
Build simpleperf failed

### ISSUE THREAD

**Issue by dslin1010** [google/android-riscv64#95]
Hi,
I want to build simpleperf for riscv. But it will have build FAILED as below: 

```
$ source build/envsetup.sh
$ lunch aosp_cf_riscv64_phone-userdebug
$ mmma system/extras/simpleperf -j30
$ mmma system/extras/simpleperf -j30
============================================
PLATFORM_VERSION_CODENAME=VanillaIceCream
PLATFORM_VERSION=VanillaIceCream
PRODUCT_INCLUDE_TAGS=com.android.mainline
TARGET_PRODUCT=aosp_cf_riscv64_phone
TARGET_BUILD_VARIANT=userdebug
TARGET_ARCH=riscv64
TARGET_ARCH_VARIANT=riscv64
TARGET_CPU_VARIANT=generic
HOST_OS=linux
HOST_OS_EXTRA=Linux-5.4.0-91-generic-x86_64-Ubuntu-18.04.5-LTS
HOST_CROSS_OS=linux_musl
BUILD_ID=AOSP.MASTER
OUT_DIR=out
============================================
[  0% 2/509] //system/extras/simpleperf:libsimpleperf_profcollect_rust rustLink rust/lib.rs
FAILED: out/soong/.intermediates/system/extras/simpleperf/libsimpleperf_profcollect_rust/android_riscv64_dylib/unstripped/libsimpleperf_profcollect_rust.dylib.so
echo "module libsimpleperf_profcollect_rust missing dependencies: libsimpleperf_profcollect" && false
module libsimpleperf_profcollect_rust missing dependencies: libsimpleperf_profcollect
[  0% 3/509] //system/extras/simpleperf:libsimpleperf_profcollect_rust strip libsimpleperf_profcollect_rust.dylib.so
FAILED: out/soong/.intermediates/system/extras/simpleperf/libsimpleperf_profcollect_rust/android_riscv64_dylib/libsimpleperf_profcollect_rust.dylib.so
echo "module libsimpleperf_profcollect_rust missing dependencies: libsimpleperf_profcollect" && false
module libsimpleperf_profcollect_rust missing dependencies: libsimpleperf_profcollect
22:57:40 ninja failed with: exit status 1

#### failed to build some targets (4 seconds) ####
```

In `prebuilts/rust/` folder, I check out to `aosp/simpleperf-release` branch, but it still have the same build  failed as above.
```
$ cd prebuilts/rust/
$ git pull 
$ git co aosp/simpleperf-release
```

**Comment by pirama-arumuga-nainar** [comment]
Simpleperf currently uses the outdated llvm in `external/llvm` which doesn't have any reasonable RISC-V support.

@yabinc is working on migrating simpleperf to a newer llvm.  ETA is ~1-2 months.  It's tracked in the google-internal issue-tracker, but will post here once it's complete.

**Comment by SiFiveHolland** [comment]
Does this mean there is ongoing effort to update the LLVM version in `external/llvm`? If so, do you know what version is being updated to? We are also interested as this, as it will be required to build the `radeonsi` driver in `external/mesa3d`.

**Comment by enh-google** [comment]
> Does this mean there is ongoing effort to update the LLVM version in external/llvm? If so, do you know what version is being updated to? We are also interested as this, as it will be required to build the radeonsi driver in external/mesa3d.

"yes and no".

the plan (aiui) for simpleperf is to switch to the *toolchain* version of llvm.

the plan for qemu is to move to a newer version of llvm (but not the "renderscript" version you see in external/ --- that would require ). the qemu work is actually pretty advanced internally (aiui) but the work to move that out to upstream and/or AOSP has (aiui) yet to start.

**Comment by dslin1010** [comment]
> Simpleperf currently uses the outdated llvm in external/llvm which doesn't have any reasonable RISC-V support.

> @yabinc is working on migrating simpleperf to a newer llvm. ETA is ~1-2 months. It's tracked in the google-internal issue-tracker, but will post here once it's complete.

Hi @pirama-arumuga-nainar ,
OK, I got it. Thanks for the update.

**Comment by enh-google** [comment]
(for googlers, http://b/267670561 "Switch simpleperf to prebuilt llvm libraries to build it on riscv" is the internal bug mentioned above.)

**Comment by enh-google** [comment]
you can build system/extras/simpleperf/ for riscv64 now. (the internal bug is still open to clean up a workaround, but _functionally_ this work is done.)

unfortunately, you can't _use_ simpleperf on qemu for lack of perf events.

**Comment by dslin1010** [comment]
Hi @enh-google ,

> you can build system/extras/simpleperf/ for riscv64 now. (the internal bug is still open to clean up a workaround, but functionally this work is done.)

Thanks for the fix. I'll try it.

> unfortunately, you can't use simpleperf on qemu for lack of perf events.

Can I ask, if is it related to the architecture code needed to port in simpleperf for RISC-V perf events?
As far as I know, the Linux perf tools at least can support the general hardware events on qemu.

**Comment by enh-google** [comment]
> Can I ask, if is it related to the architecture code needed to port in simpleperf for RISC-V perf events?

i don't actually know, since i'm not very familiar with qemu (and our perf events expert isn't around today). i'd assume qemu doesn't support them though, because what use would they be? i assume you're thinking of the virtualized case, where the perf events are fairly meaningful?

**Comment by dslin1010** [comment]
OK, I got it. Thanks.

**Comment by SiFiveHolland** [comment]
Will the android/riscv64 build of simpleperf eventually be included in the NDK? I don't see it in the latest build artifact from https://ci.android.com/builds/branches/aosp-master-ndk/grid?legacy=1.

**Comment by pirama-arumuga-nainar** [comment]
Yes, we'll eventually add these to the NDK.  There's still some pending work to package this in the NDK.

**Comment by pirama-arumuga-nainar** [comment]
In https://r.android.com/2848836, @yabinc added a simpleperf binary for riscv64.
