### ISSUE TITLE
Question about video play

### ISSUE THREAD

**Issue by rayeh5** [google/android-riscv64#96]
When I play video, the output color seems wrong?
Please refer to the attachment.
Thanks for your time.

![video_pic](https://github.com/google/android-riscv64/assets/5005947/166b7cae-4676-4967-9457-c9e44ed9d344)

**Comment by enh-google** [comment]
what format of video? played with what?

**Comment by rayeh5** [comment]
the video file is as attachment.
I push into the cuttlefish, then use mouse to click it to play this file.
https://github.com/google/android-riscv64/assets/5005947/9f10b7c7-7966-4f3e-8742-48bac769d5ff

**Comment by negge** [comment]
Hi @rayeh5, I see in https://github.com/google/android-riscv64/issues/38#issuecomment-1581824786 that a fix for libyuv was cherrypicked into AOSP. Can you rebuild and check if this fixes the issue for you?

**Comment by rayeh5** [comment]
Any comment for this issue? It seems the "Blue" color is missing when play video file.

**Comment by rayeh5** [comment]
I build aosp_cf_x86_64_phone-userdebug, aosp_cf_riscv64_phone-userdebug and aosp_cf_arm64_phone-userdebug by using the same source, the output color of video is correct for x86_64 version, the arm64 and riscv64 are the same with wrong color.
Any comment?

**Comment by jmacnak** [comment]
@rayeh5: Could you share more information about how you are launching the Cuttlefish instances, about the enviroment the Cuttlefish instances are running in (mostly just interested in whether or not you are using the default `--gpu_mode=auto` and whether or not it is detecting acceleration support), and about how you are interacting with the Cuttlefish instances (which VNC client)?

![image](https://github.com/google/android-riscv64/assets/3465506/b080330b-7158-45c7-865a-38388526ec11)

^ This is `aosp_cf_arm64_phone-userdebug` using `cvd start --gpu_mode=guest_swiftshader --vm_manager=qemu_cli` and interacting with the instance via TightVNC.

**Comment by rayeh5** [comment]
The problem should be caued by "--gpu_mode=drm_virgl".
By using "--gpu_mode=guest_swiftshader" and TightVNC, the "black and white" video is normal.
Use "scrcpy" program to connect to Cuttlefish, the video is normal.
But with color video, the TightVNC has problem to show correct color.
The TightVNC shows the following message:
------
Connected to RFB server, using protocol version 3.8
No authentication needed
Authentication successful
Desktop name "QEMU (cvd-1)"
VNC server default format:
  32 bits per pixel.
  Least significant byte first in each pixel.
  True colour: max red 255 green 255 blue 255, shift red 16 green 8 blue 0
Using default colormap which is TrueColor.  Pixel format:
  32 bits per pixel.
  Least significant byte first in each pixel.
  True colour: max red 255 green 255 blue 255, shift red 16 green 8 blue 0
Same machine: preferring raw encoding
-------------------------

**Comment by jmacnak** [comment]
Ack, thanks for the info. I might not get to looking at this until next week.

**Comment by rayeh5** [comment]
got it and thanks!
